### ISSUE TITLE
Can't encode a non-empty HashMap with tuple keys

### ISSUE THREAD

**Issue by rsaarelm** [rust-lang-nursery/rustc-serialize#132] opened 2015-10-07 08:32 UTC
How to reproduce:

example.sh:

``` bash
#!/bin/bash

cat > Cargo.toml <<EOF
[package]
name = "encode-test"
version = "0.1.0"
authors = [ "Your Friendly Unit Tester" ]

[dependencies]
rustc-serialize = "0.3.16"
EOF

mkdir -p src
cat > src/main.rs <<EOF
extern crate rustc_serialize;

fn main() {
    use std::collections::HashMap;
    use rustc_serialize::json;

    let mut x: HashMap<(i32, i32), i32> = HashMap::new();
    // This works:
    json::encode(&x).expect("Can't serialize an empty hashmap with a tuple key");
    x.insert((1, 2), 3);
    // This doesn't:
    json::encode(&x).expect("Can't serialize a hashmap with a tuple key when there's data in it");
}
EOF

RUST_BACKTRACE=1 cargo run
rustc --version
```

Result:

```
$ ./example.sh
   Compiling encode-test v0.1.0 (file:///home/rsaarelm/tmp/encodefail)
     Running `target/debug/encode-test`
thread '<main>' panicked at 'Can't serialize a hashmap with a tuple key when there's data in it: BadHashmapKey', ../src/libcore/result.rs:755
stack backtrace:
   1:     0x56114937c869 - sys::backtrace::tracing::imp::write::hc20cecbe7cbc162bPnt
   2:     0x56114937ba48 - panicking::on_panic::h838652421a384701enx
   3:     0x5611493780fe - sys_common::unwind::begin_unwind_inner::h1941327c7a60c738ffs
   4:     0x5611493785a8 - sys_common::unwind::begin_unwind_fmt::h4031d684ed7c61dales
   5:     0x56114937b2c1 - rust_begin_unwind
   6:     0x5611493a694f - panicking::panic_fmt::hbc88432c478178b9KgG
   7:     0x56114936bede - result::Result<T, E>::expect::h17010704537153362598
                        at ../src/libcore/macros.rs:28
   8:     0x56114936a042 - main::h5e3b2f17d53a5276faa
                        at src/main.rs:12
   9:     0x56114937e3a4 - sys_common::unwind::try::try_fn::h9804440597480785666
  10:     0x56114937b128 - __rust_try
  11:     0x56114937e018 - rt::lang_start::hcf64c98c1a7c0031Zkx
  12:     0x5611493768f6 - main
  13:     0x7f1d27c3060f - __libc_start_main
  14:     0x561149369e68 - _start
  15:                0x0 - <unknown>
An unknown error occurred

To learn more, run the command again with --verbose.
rustc 1.4.0-beta.2 (4b9b1f3b0 2015-10-01)
```

**Comment by rsaarelm** [comment] 2015-10-07 08:51
After talking about this on IRC, apparently this is by design in the JSON encoder backend, which limits map keys to JSON types. I don't know if this is documented anywhere, so leaving the issue up for now.

**Comment by blindley** [comment] 2015-10-26 17:04
Was about to report that I can't serialize a HashMap with a custom key type. But I suppose the issue is the same.

    extern crate rustc_serialize;
    
    fn main() {
        use rustc_serialize::json;
        use std::collections::HashMap;
        
        let mut v: HashMap<Id, i32> = HashMap::new();
        v.insert(Id { x: 10 }, 100);
    
        json::encode(&v).unwrap();
    }
    
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, RustcEncodable, RustcDecodable)]
    struct Id {
        pub x: i32,
    }

Compiles and runs with:

    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: BadHashmapKey', ../src/libcore\result.rs:736

**Comment by alexcrichton** [comment] 2017-04-21 14:07
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.

**Closed by alexcrichton** 2017-04-21 14:07 UTC
