### ISSUE TITLE
Segfault with only safe code

### ISSUE THREAD

**Issue by dten** [rust-lang-nursery/rustc-serialize#160] opened 2016-07-28 00:06 UTC
I'm running into some code that causes a segfaults and I'm not sure if it's me (doesn't seeeem it though) or it's rustc_serialize or if it's a rust bug

[seg_example.zip](https://github.com/rust-lang-nursery/rustc-serialize/files/387422/seg_example.zip)

very simple example here segfaults on cargo test. the only complication is there's a crate and a sub crate both using rustc_serialize. if i move the decodable type form the sub-crate to the main one it does not, if i remove some fields it does not, if i do most other things it does not segfault.

**Comment by BurntSushi** [comment] 2016-07-28 00:08
Could you please post your code in the issue itself?

Judging from your description of the problem, this sounds like a dupe of #154.

**Comment by dten** [comment] 2016-07-28 00:15
So I have one crate that exports a decodable type

```
extern crate rustc_serialize;

#[derive(RustcDecodable)]
pub struct File {
    pub id: String,
    pub title: String,
}
```

and another crate that uses the exported type in it's own type.

the test segfaults

```
extern crate rustc_serialize;
pub extern crate other_crate as api;

use api::File;
use rustc_serialize::{Decodable, Decoder};

pub enum Event {
    FileShared {
        file: File,
    },
}

impl Decodable for Event {
    fn decode<D: Decoder>(d: &mut D) -> Result<Event, D::Error> {
        Ok(Event::FileShared { file: try!(d.read_struct_field("file", 0, |d| Decodable::decode(d))) })
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use rustc_serialize::json;

    #[test]
    fn decode_lame_file() {
        let _ = json::decode::<Event>(r#"{ "file": { "id": "F1VQBMZ26" } }"#);
    }
}
```

**Comment by dten** [comment] 2016-07-28 00:19
that other issue does seem identical thanks

**Comment by alexcrichton** [comment] 2017-04-21 14:08
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.

**Closed by alexcrichton** 2017-04-21 14:08 UTC
